### ISSUE TITLE
wsgi.py fails on runserver

### ISSUE THREAD

**Issue by jfmatth** [jfmatth/openshift-django17#11]
Since the last commit, looks like the settings.py for wsgi application causes it to fail on local runserver.

should be able to remove it from settings.py as only runserver uses it.

**Comment by Szypek** [comment]
Hi,
You need to change WSGI_APPLICATION variable to 'wsgi.wsgi.application' and add __init__.py to wsgi folder for Django to see it as a package. After that it should run.
Hope it helps :)

**Comment by ilyaglar** [comment]
Yes, just removing string WSGI_APPLICATION = 'mysite.wsgi.application' and works correct.

**Comment by jfmatth** [comment]
Thanks for confirming.

**Comment by willv** [comment]
I would suggest not removing it but to add this condition:
if ON_PAAS: 
    WSGI_APPLICATION = 'mysite.wsgi.application'

**Comment by jfmatth** [comment]
Willv, thanks.

Actually, the setting is a 'left-over' since when running 'runserver' it's not used (really).

**Comment by jfmatth** [comment]
I am open to pull requests.

**Comment by jfmatth** [comment]
Pull seems to do the trick, thanks Niall
