### ISSUE TITLE
Python 3.3 support

### ISSUE THREAD

**Issue by ZoltanOnody** [jfmatth/openshift-django17#12]
Hey, could you please make repository also for python 3.3 with Django 1.7?

**Comment by jfmatth** [comment]
It should be somewhat 3.3 compatible, have you found something that isn't?

Point it out and I'll do what I can

**Comment by ZoltanOnody** [comment]
It works, I should have tried it before I wrote here. Sorry for wasting your time.

**Comment by jfmatth** [comment]
Not a waste of time, always looking for feedback
