### ISSUE TITLE
" 'DEBUG' in os.environ " expression always return 'True'

### ISSUE THREAD

**Issue by caitong93** [jfmatth/openshift-django17#13]
In setting.py
`DEBUG = DEBUG or 'DEBUG' in os.environ`
which should be
    ```DEBUG = DEBUG or `DEBUG` in os.environ and os.environ['DEBUG'] == `True````

**Comment by jfmatth** [comment]
HI Caitong93, thanks for having a look at my repo.

I'm not sure I see any improvement in your logic vs. mine?  The only different seems to be that DEBUG should be the string "True" but with mine, it could be anything, as long as it just exists in the environment.

If you'd like to show me some examples and submit a pull request, i'll consider it.

thanks again,

John

**Comment by caitong93** [comment]
Oh, I misunderstood it.After first push, I set DEBUG to 'False' attempting to disable debug...Actually, I can delete that..Forget it..
And, thanks for your repo, great help!

**Comment by jfmatth** [comment]
No worries.

Thanks for the appreciation.

I'm going to start a branch for v1.8 beta that was just announced, and incorporate my other issues into that branch.

J
