### ISSUE TITLE
git history for new projects

### ISSUE THREAD

**Issue by riggs** [jfmatth/openshift-django17#15]
The template has worked flawlessly on python 3.3. The only issue I've run into is that, because I cloned this repo to set up the initial framework, I have the git history from this project attached to my work. I still want to give credit where credit is due (especially for the .openshift directory!), including via git history, but 91 commits that are wholly unrelated to my project is misleading. (Not to mention overshadowing the 50ish commits I've made since then. My poor ego!)

The best idea I currently have is to use the interactive git rebase to squash all 91 into 1. That feels, to put it mildly, clumsy. Any idea on a better solution? And one that would be simple for folks to do immediately after they clone this repo that could be added to the instructions?

**Comment by jfmatth** [comment]
Benjamin,

Thanks for using the repo, glad it's working for 3.3 (not my work though, others).

I don't have a better idea for you, and honestly if you fork it and rebase, I'm ok with that.

At some point (probably django 2.0) I'll probably check in a new version with that idea, but until then, it's working for people.

J

**Comment by jfmatth** [comment]
Going to close this and open a new enhancement to remove history.
