### ISSUE TITLE
Service Temporarily Unavailable

### ISSUE THREAD

**Issue by JernejJerin** [jfmatth/openshift-django17#16]
First I would like to thank you for this repository. I have also been using your previous repository openshift-django16. Thank you!

But I do have some problems with this version. After approximately running successfully for 6h I get the following error:

>Service Temporarily Unavailable
>The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

After I restart the application it works without any problem for some hours, then I get this error again. Before I moved to Django 1.7, I was using your previous repository for openshift-django16 and I did not have this problem.

**Comment by jfmatth** [comment]
Jernej,

Thanks for the compliments, I'm glad it helps you. 

The problem you're describing sounds like the OS free plan shutting down your application due to idle time?  I had a similar issue with my site.

couple of questions:
- Are you load balanced?
- Are you on the Openshift free plan.
- is the 1.6 code THE SAME as the 1.7 code?
- What do the logs show from either python or HAproxy (if LB).

If you are on the free plan, may I suggest you switch to Bronze, if nothing more than to get away from Idle gears.  I use the Bronze plan for both that, and the 1GB of disk I need (at a whooping $.90 /month).

if you can answer those above and I'll see what I can do.  Thanks again for enjoying my repo.

**Comment by JernejJerin** [comment]
Answers to your questions:
* Yes I do have Web Load Balancer
* Yes I am on the Openshift free plan
* The application code is the same

Now gears should never enter idle mode, as I am posting some data every 5 minutes through RESTful API. However I do agree about switching to Bronze mode.

I have run rhc tail command and I think the error lies in HaProxy:

> ==> app-root/logs/haproxy.log <==
[WARNING] 081/155915 (497777) : config : log format ignored for proxy 'express'
since it has no log address.
[WARNING] 081/155915 (497777) : Server express/local-gear is DOWN, reason: Layer
4 connection problem, info: "Connection refused", check duration: 0ms. 0 active
and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[ALERT] 081/155915 (497777) : proxy 'express' has no server available!
[WARNING] 081/155948 (497777) : Server express/local-gear is UP, reason: Layer7
check passed, code: 200, info: "HTTP status check returned code <3C>200<3E>", ch
eck duration: 11ms. 1 active and 0 backup servers online. 0 sessions requeued, 0
 total in queue.
[WARNING] 081/170359 (127633) : config : log format ignored for proxy 'stats' si
nce it has no log address.
[WARNING] 081/170359 (127633) : config : log format ignored for proxy 'express'
since it has no log address.
[WARNING] 081/170359 (497777) : Stopping proxy stats in 0 ms.
[WARNING] 081/170359 (497777) : Stopping proxy express in 0 ms.
[WARNING] 081/170359 (497777) : Proxy stats stopped (FE: 1 conns, BE: 0 conns).
[WARNING] 081/170359 (497777) : Proxy express stopped (FE: 206 conns, BE: 312 co

I also run some CRON job once a day, but I am 99% sure it does not have to do anything with this. It looks like a problem on Openshift side, right?

**Comment by jfmatth** [comment]
Hmm, very odd indeed.

I would suggest relaunching this code on another application and see if u see the same behavior.

I've had DNS issues in the past which propagated in the same manner, but my app (django) would alert that it couldn't talk to the DB.  Red Hat was able to move my instance around, but that shouldn't be needed in your case, just redeploy to a new application and see what happens

Also, you might Google stackoverflow to see if others see this HA issue.

**Comment by jfmatth** [comment]
I just noticed the 'connection refused', do you know what that is from?

Where is the RESTfull call coming from, itself or another gear that's outside of that app?

J

**Comment by JernejJerin** [comment]
The RESTful POST call is coming outside of the app. I will post this issue on stackoverflow. Thanks for your help!
